mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tabor/', include('tabor.urls' , namespace='tabor')),
]

mysite/tabor/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^deset4neb/(?P<turn_id>[0-9]+)$', views.destBoduProNebelvir_view, name='deset4neb'),
    url('^fci_home/(?P<turn_id>[0-9]+)$', views.fci_home_view, name='fci_home'),
    url('^notice_board/(?P<turn_id>[0-9]+)$', views.notice_board, name='notice_board'),
    url('^issue_list/(?P<turn_id>[0-9]+)$', views.issue_list_view, name='issue_list'),
    url('^issue_change_status/(?P<turn_id>[0-9]+)$', views.issue_change_status, name='issue_change_status'),
    url('^issue_list_new/(?P<turn_id>[0-9]+)$', views.issue_list_new, name='issue_list_new'),
    url('^fci_settings/(?P<turn_id>[0-9]+)$', views.game_settings_view, name='fci_settings'),
    url('^fci_details/(?P<turn_id>[0-9]+)$', views.fci_details_view, name='fci_details'),
    url('^new_init_con/(?P<turn_id>[0-9]+)$', views.game_new_init_con, name='new_init_con'),
    url('^restart/(?P<turn_id>[0-9]+)$', views.game_start, name='restart'),
    url('^return_to_day/(?P<turn_id>[0-9]+)$', views.pay_day_return, name='return_to_day'),
    url('^new_pay_day/(?P<turn_id>[0-9]+)$', views.pay_days_new, name='pay_days_new'),
    url('^fci_team/(?P<team_id>[0-9]+)$', views.fci_team_view, name='fci_team'),
    url('^accounts/', include('django.contrib.auth.urls')),
    url('^rate/(?P<band_id>[0-9]+)$',views.rate,name='rate'),
    url('^employ/(?P<team_id>[0-9]+)$',views.employ,name='employ'),
    url('^time_table/(?P<turn_id>[0-9]+)$', views.time_table_view, name='time_table'),
    url('^time_table/add/(?P<turn_id>[0-9]+)$', views.time_table_add, name='time_table_add'),
    url('^time_table/(?P<rehersal_id>[0-9]+)$/edit$', views.time_table_edit, name='time_table_edit'),
    url('^time_table/(?P<rehersal_id>[0-9]+)$/remove$', views.time_table_delete, name='time_table_delete'),


]

mysite/tabor/views/views_base.py
#QyD9G8h0wg


from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import Group

import datetime
import json
from tabor.models import  FCITeam, FCICeleb,Band,InitCondition,PayDay, BasicContent, Member, Turn, FCISite,Issue, IssueStatus,IssueType, PayDayTeamHistory, Rehearsal, RehearsalRoom
from django.core.urlresolvers import resolve


def commonArgs(request):
    turn_list = Turn.objects.filter(visible=True)
    current_url = resolve(request.path_info).url_name
    current_url_full =  "tabor:"+current_url
    vedouci= Group.objects.get(id=1)
    print(current_url_full)
    return {'turn_list': turn_list.order_by('start'),'user':request.user, 'current_url':current_url_full, 'vedouci': vedouci}



def destBoduProNebelvir_view(request,turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    bands_at_turn = Band.objects.filter(turn=sel_turn)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    args.update({'bands': bands_at_turn.order_by('score').reverse()})
    return render(request, 'deset4neb.html', args)




def index(request):
    visible_turns=Turn.objects.filter(visible=1)
    if visible_turns.count() > 0:
        return HttpResponseRedirect(reverse('tabor:deset4neb', args=(visible_turns[0].pk,)))
    else:
        return HttpResponse("No visible turns in database")



def rate(request, band_id):
    band = get_object_or_404(Band, pk=band_id)
    band.score+= int(request.POST['points'])
    band.save()
    return HttpResponseRedirect(reverse('tabor:deset4neb', args=(band.turn.id,)))

def notice_board(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    notice_board = BasicContent.objects.get(title='Nástěnka')
    args.update({'notice_board': notice_board})
    return render(request, 'notice_board.html', args)

mysite/tabor/views/views_cal.py
#QyD9G8h0wg


from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
import json
from tabor.models import  Band, Member, Turn, Rehearsal, RehearsalRoom
from .views_base import commonArgs



def time_table_view(request,turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    bands = Band.objects.filter(turn=sel_turn)
    args.update({'turns_bands': bands})

    try:
        member=Member.objects.get(user=request.user)
        args.update({'members_bands': member.band_set.all()})
        args.update({'member': member})
        print(member.band_set.all())
    except Member.DoesNotExist:
        args.update({'members_bands': []})
        args.update({'member': []})

    bands_data = {}
    for band in bands:
        bands_data.update((band.serializable_object()))

    bands_data=get_bands()
    args.update({'bands_data': bands_data})

    valid_times=[{"start": "09:30", "end": "12:00"}, {"start": "14:30", "end": "18:00"}, {"start": "19:30", "end": "21:30"}]
    args.update({'valid_times':json.dumps(valid_times)})

    rehearsals = Rehearsal.objects.all
    args.update({'rehearsals': rehearsals})
    rehearsal_rooms = RehearsalRoom.objects.all
    args.update({'rehearsal_rooms': rehearsal_rooms})


    return render(request, 'time_table.html', args)


def time_table_api(request,turn_id):
    return 0





def get_bands():
    json_data={"1": {"id": 1, "name": "Muller Mix", "rehearsal_room": "A", "is_project": 0,
           "members": {"20064": {"name": "Sára  Davisonová", "is_guest": 0},
                       "20255": {"name": "Anna Mullerová", "is_guest": 0},
                       "20256": {"name": "Jana Mullerová", "is_guest": 0},
                       "20882": {"name": "Daniel Kadera", "is_guest": 0}}},
     "2": {"id": 2, "name": "Druhá", "rehearsal_room": "B", "is_project": 0,
           "members": {"20647": {"name": "Hana Mikolášová", "is_guest": 0}, "20669": {"name": "Jan Eis", "is_guest": 0},
                       "20878": {"name": "Agáta Šarochová", "is_guest": 0}}},
     "3": {"id": 3, "name": "Implantáty vod Pantáty", "rehearsal_room": "F", "is_project": 0,
           "members": {"20356": {"name": "Lucie Landová", "is_guest": 0},
                       "20528": {"name": "Veronika Dibelková", "is_guest": 0}}},
     "4": {"id": 4, "name": "Brunejský sultán", "rehearsal_room": "G", "is_project": 0,
           "members": {"20064": {"name": "Sára  Davisonová", "is_guest": 0},
                       "20255": {"name": "Anna Mullerová", "is_guest": 0},
                       "20882": {"name": "Daniel Kadera", "is_guest": 0},
                       "22132": {"name": "David  Václavík", "is_guest": 0}}},
     "5": {"id": 5, "name": "Testovací Trio", "rehearsal_room": "F", "is_project": 0,
           "members": {"20064": {"name": "Sára  Davisonová", "is_guest": 0},
                       "20669": {"name": "Jan Eis", "is_guest": 0}, "20878": {"name": "Agáta Šarochová", "is_guest": 0},
                       "20916": {"name": "Jakub Bureš", "is_guest": 0}}}}
    return  json.dumps(json_data)



def time_table_add(request,turn_id):
    print("ouu jee")
    print(request.__str__())
    return HttpResponseRedirect(reverse('tabor:time_table', args=(turn_id,)))


def time_table_edit(request):
    print(request.__str__())

def time_table_delete(request):
    print(request.__str__())

mysite/tabor/views/views_fci_game.py
#QyD9G8h0wg


from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import Group

import datetime
import json
from tabor.models import  FCITeam, FCICeleb,Band,InitCondition,PayDay, BasicContent, Member, Turn, FCISite,Issue, IssueStatus,IssueType, PayDayTeamHistory, Rehearsal, RehearsalRoom
from django.core.urlresolvers import resolve
from .views_base import commonArgs


def fci_home_view(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    fci_teams_at_turn = FCITeam.objects.filter(turn=sel_turn)
    args.update({'fci_teams': fci_teams_at_turn})
    celebs=FCICeleb.objects.filter(team__in=fci_teams_at_turn)
    args.update({'sites': FCISite.objects.all()})
    args.update({'celebs': celebs})
    args.update({'sel_turn': sel_turn})
    args.update({'jobless': celebs.filter(site=None)})
    pay_days = PayDay.objects.filter(turn=sel_turn)
    args.update({'pay_days': pay_days})
    return render(request, 'fci_home.html', args)



def employ(request, team_id):
    celeb = get_object_or_404(FCICeleb, id=int(request.POST['celeb_id']))
    site_id=int(request.POST['site_id'])


    if site_id!=-1:
        site = get_object_or_404(FCISite, id=int(site_id))
        vir = int(request.POST['viral_id'])
        celeb.mult_vir = vir
        celeb.site = site
    else:
        celeb.mult_vir = 0
        celeb.site = None

    celeb.save()
    return HttpResponseRedirect(reverse('tabor:fci_team', args=(team_id,)))


def fci_team_view(request, team_id):
    sel_team = FCITeam.objects.get(id=team_id)
    sel_turn = sel_team.turn
    celebs= FCICeleb.objects.filter(team=sel_team)
    args=commonArgs(request)
    args.update({'team': sel_team, 'celebs': celebs, 'sel_turn': sel_turn})
    args.update({'sites': FCISite.objects.all()})
    return render(request, 'fci_team.html', args)


def pay_days_view(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    pay_days=PayDay.objects.filter(turn=sel_turn)
    args.update({'pay_days': pay_days})
    return render(request, 'fci_pay_days.html', args)


def make_dough(sel_turn, user):

    celebs = FCICeleb.objects.all()

    for celeb in celebs:
        if celeb.team.turn == sel_turn:
            celeb.update()

    pay_day = PayDay(moment=datetime.datetime.now(), turn=sel_turn, user=user)
    pay_day.save()

    for celeb in celebs:
        if celeb.team.turn == sel_turn:
            celeb.backup(pay_day)

    teams = FCITeam.objects.filter(turn=sel_turn)
    for team in teams:
        team.backup(pay_day)


def pay_days_new(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    make_dough(sel_turn=sel_turn, user=request.user.__str__())
    return HttpResponseRedirect(reverse('tabor:fci_home', args=(turn_id,)))


def pay_day_return(request,turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    pay_day=get_object_or_404(PayDay, id=int(request.POST['pay_day_id']))
    pay_day.restore()
    return HttpResponseRedirect(reverse('tabor:fci_home', args=(turn_id,)))

def game_settings_view(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    init_conds = InitCondition.objects.filter(turn=sel_turn)
    args.update({'init_conds': init_conds})

    ids = []
    for init_cond in init_conds:
        ids += [init_cond.celeb.id]

    pay_days = PayDay.objects.filter(turn=sel_turn)
    args.update({'pay_days': pay_days})
    celebs = FCICeleb.objects.exclude(id__in =ids)
    args.update({'celebs': celebs})
    teams = FCITeam.objects.filter(turn=sel_turn)
    args.update({'teams': teams})
    return render(request, 'fci_settings.html', args)


def game_start(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    celebs = FCICeleb.objects.all()
    for celeb in celebs:
        celeb.reset()

    teams=FCITeam.objects.filter(turn=sel_turn)
    for team in teams:
        team.reset()

    init_conds=InitCondition.objects.filter(turn=sel_turn)
    for init_cond in init_conds:
        init_cond.apply()


    PayDay.objects.filter(turn=sel_turn).delete()
    return HttpResponseRedirect(reverse('tabor:fci_home', args=(turn_id,)))


def game_new_init_con(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    celeb = get_object_or_404(FCICeleb, id=int(request.POST['celeb_id']))
    team = get_object_or_404(FCITeam, id=int(request.POST['team_id']))
    init_con=InitCondition(turn=sel_turn,team=team,celeb=celeb)
    init_con.save()
    return HttpResponseRedirect(reverse('tabor:fci_settings', args=(turn_id,)))




    return render(request, 'issue_list.html', args)


def fci_details_view(request,turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    teams=FCITeam.objects.filter(turn=sel_turn)
    pay_days = PayDay.objects.filter(turn=sel_turn).order_by('moment')
    pay_day_lines=[]
    for pay_day in pay_days:
        pay_day_line=[pay_day.moment.time]
        for tm in teams:
            history = PayDayTeamHistory.objects.filter(pay_day=pay_day)
            print(tm.money)
            team_history = history.filter(team=tm)
            money=team_history.get().money
            pay_day_line+=[money]

        pay_day_lines+=[pay_day_line]

    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    args.update({'pay_day_lines': pay_day_lines})
    args.update({'teams': teams})
    return render(request, 'fci_details.html', args)

mysite/tabor/views/views_management.py
#QyD9G8h0wg


from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
import datetime
from tabor.models import  FCITeam, FCICeleb,Band,InitCondition,PayDay, BasicContent, Member, Turn, FCISite,Issue, IssueStatus,IssueType, PayDayTeamHistory, Rehearsal, RehearsalRoom
from .views_base import commonArgs



def issue_list_new(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    typ = IssueType.objects.get(id=request.POST['type_id'])
    status = IssueStatus.objects.get(id=3)
    body = request.POST['notice']
    issue= Issue(author=request.user.__str__(), body=body, status=status, type=typ,moment=datetime.datetime.now())
    issue.save()
    return HttpResponseRedirect(reverse('tabor:issue_list', args=(turn_id,)))


def issue_change_status(request, turn_id):
    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    issue= Issue.objects.get(id=request.POST['issue_id'])
    try:
        status = IssueStatus.objects.get(label=request.POST['status_label'])
        print(issue.__str__() + " status changed to " +status.__str__())
    except IssueStatus.DoesNotExist:
        print(issue.__str__() + " issue will be deleted")
        status = None

    issue.status=status
    issue.save()
    return HttpResponseRedirect(reverse('tabor:issue_list', args=(turn_id,)))


def issue_list_view(request, turn_id):

    issues = Issue.objects.all()

    if request.POST.get('filter_type_id', False):
        try:
            itype = IssueType.objects.get(id=request.POST['filter_type_id'])
            issues = issues.filter(type=itype)
        except IssueType.DoesNotExist:
            print("no type selected")

    if request.POST.get('filter_status_id', False):
        try:
            status = IssueStatus.objects.get(id=request.POST['filter_status_id'])
            print("filter status:" + status.label)
            issues = issues.filter(status=status)
        except IssueStatus.DoesNotExist:
            print("no status selected")

    sel_turn = Turn.objects.get(id=turn_id)
    args = commonArgs(request)
    args.update({'sel_turn': sel_turn})
    args.update({'issues': issues})
    issue_types = IssueType.objects.all
    args.update({'issue_types': issue_types})
    issue_statuses = IssueStatus.objects.all
    args.update({'issue_statuses': issue_statuses})


    return render(request, 'issue_list.html', args)

mysite/tabor/templates/fci_settings.html
{% extends "skelet.html" %}
{% block title %}Hudebni tabor{% endblock %}
{% block content %}
{% load static %}
{% if vedouci in user.groups.all%}



<div class="row">
    <h5>ŘÍDÍCÍ PANEL TEMELÍN</h5>
    <div class="divider"></div>
    <div class="section">
        <div class="row align: center">
        <h5>Pokud nevíš co tohle tlačítko dělá, tak ho nemačkej!</h5>
        <a href="{%url 'tabor:pay_days_new' sel_turn.id %}" class="waves-effect waves-light btn-large red darken-2">
        <i class="material-icons right">error</i>
        <i class="material-icons left">error</i>
        <i class="material-icons right">error</i>
        <i class="material-icons left">error</i>

        VÝPLATA </a>
        </div>
    </div>
    <div class="section">

       <ul class="collection with-header">
        <li class="collection-header"><h4>Počáteční podmínky</h4>
      </li>

      {% for init_cond in init_conds %}

        <li class="collection-item">
            <div class = "row">
                <div class="col s4">
                 {{init_cond.celeb}}
                    <span class="new badge color {{init_cond.team.colour}}" data-badge-caption="">{{init_cond.team.name}}</span>

                </div>

                    <a href="#!" class="secondary-content">
                 <i class="material-icons">delete</i></a>

            </div>
        </li>
      {% endfor %}

      </ul>


            <div class="row">

             <form action="{% url 'tabor:new_init_con' sel_turn.id %}" method="post">
                    {% csrf_token %}
                    <div class="col s2 align: center">
                        <i class="material-icons left">perm_contact_calendar</i>
                        Nová podmínka:
                    </div>
                   <div class="input-field col s4">
                        <select name="team_id">
                            <option value="-1"  selected>---</option>
                            {% for team in teams %}
                            <option value="{{team.id}}">{{team.name}}</option>
                            {% endfor %}
                        </select>
                        <label>Team</label>
                    </div>
                   <div class="input-field col s4">
                        <select name="celeb_id">
                             <option value="-1"  selected>---</option>
                            {% for celeb in celebs %}

                            <option value="{{celeb.id}}">{{celeb}}</option>
                            {% endfor %}

                        </select>
                        <label>Postava</label>
                    </div>
                   <div class="col s2 align: center">

                        <button class="btn waves-effect"><i class="material-icons">input</i></button>
                    </div>
            </form>

            </div>
            <div class="divider"/>








    </div>

    <div class="row align: center">

        <h5>Pokud nevíš co tahle tlačítka dělají, tak je nemačkej! Důsledky jsou nevratné</h5>


    <div class="col s12 m6">
        <a href="{%url 'tabor:restart' sel_turn.id %}" class="waves-effect waves-light btn-large red darken-2">
        <i class="material-icons right">error</i>
        <i class="material-icons left">error</i>
        <i class="material-icons right">error</i>
        <i class="material-icons left">error</i>
        <i class="material-icons right">error</i>
        <i class="material-icons left">error</i>
        HARD FATAL RESET / START</a>

    </div>

    <div class="col s12 m6">

    <div class="row">

             <form action="{% url 'tabor:return_to_day' sel_turn.id %}" method="post">
                    {% csrf_token %}

                   <div class="input-field col s6">
                        <select name="pay_day_id">
                            <option value="-1"  selected>---</option>
                            {% for pay_day in pay_days %}
                            <option value="{{pay_day.id}}">{{pay_day}}</option>
                            {% endfor %}
                        </select>
                        <label>Výplata</label>
                    </div>

                   <div class="col s6 align: center">
                        <button class="waves-effect waves-light btn-large red darken-2">
                                RESTORE
                              <i class="material-icons right">error</i>
                              <i class="material-icons left">error</i>
                            </button>
                    </div>
            </form>


    </div>

</div>
{% endif %}
{% endblock %}

mysite/tabor/templates/fci_team.html
{% extends "skelet.html" %}
{% block title %}Hudebni tabor{% endblock %}
{% block content %}
{% load static %}
<div class="section">
    <h4 class="header">{{team.name}} $ {{team.money}} .00</h4>
        <ul class="collection">
           {% for member in team.members.all %}
          <li class="collection-item">{{member.name}}</li>

        {% endfor%}
        </ul>

</div>

<div class="row">
    <div class="col s12 m6">
           {% for celeb in celebs %}

        <div class="card white ">
            <div class="card-content">
                <div class="row">
                    <span class="card-title">{{celeb.name}}</span>
                    <h6 class="bold">FREE = {{celeb.mult_free}}, COOL = {{celeb.mult_cool}}, IN = {{celeb.mult_in}}, VIRAL = {{celeb.mult_vir}}</h6>
                        </div>
                            <blockquote>
                               <p>{{celeb.story}}</p>
                            </blockquote>
                            {% if celeb.site%}
                            <p><i class="material-icons left">my_location</i> {{celeb.site}} </p>
                            {% endif%}
                        </div>

            {% if vedouci in user.groups.all%}
            <div class="divider"></div>
            <br>

            <div class="row">
            <div class="col s12">


               <form action="{% url 'tabor:employ' team.id %}" method="post">
                    {% csrf_token %}
                    <div class="col s1">
                        <i class="material-icons left">settingsn</i>
                    </div>
                   <div class="input-field col s5">
                        <select name="site_id">
                            <option value="-1"  selected>---</option>
                            {% for site in sites %}
                            <option value="{{site.id}}">{{site}}</option>
                            {% endfor %}
                        </select>
                        <label>Vyber zaměstnání</label>
                    </div>
                   <div class="input-field col s3">
                        <select name="viral_id">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>

                        </select>
                        <label>Viralita</label>
                    </div>
                   <div class="col s3">
                        <input type="hidden" name="celeb_id" value="{{celeb.id}}">
                        <button class="btn waves-effect"><i class="material-icons">input</i></button>
                    </div>
                </form>

            </div>
            </div>
            {% endif %}

        </div>

            {%endfor%}
    </div>

    <div class="col s12 m6">

    </div>
</div>



{% endblock %}

mysite/tabor/templates/issue_list.html
{% extends "skelet.html" %}
{% block title %}Hudebni tabor{% endblock %}
{% block content %}
{% load static %}
{% if vedouci in user.groups.all%}
<div class="section">
    <h4 class="header">Issue list</h4>
    <div class="divider"></div>


    <ul class="collapsible" data-collapsible="accordion">

      <li>
        <div class="collapsible-header">
                        <i class="material-icons">settings_input_composite</i>


            Filter

        </div>
        <div class="collapsible-body">


            <form action="{% url 'tabor:issue_list' sel_turn.id %}" method="post">
                    {% csrf_token %}
                   <div class="row ">

                   <div class="col s12 m6">
                        <div class="input-field">
                        <select  name="filter_type_id">
                            <option value=-1>---</option>
                            {% for issue_type in issue_types %}
                            <option value="{{issue_type.id}}">{{issue_type.label}}
                            </option>

                            {% endfor %}
                        </select>
                        <label>Typ</label>
                        </div>

                       <div class="input-field">
                        <select  name="filter_status_id">
                            <option value=-1>---</option>
                            {% for issue_status in issue_statuses %}
                            <option value="{{issue_status.id}}">{{issue_status.label}}
                            </option>

                            {% endfor %}
                        </select>
                        <label>Status</label>
                        </div>


                   </div>




                   <div class="input-field col s12 m6 align: center">
                         <button class="btn waves-effect">Filter</button>
                         <a href="{% url 'tabor:issue_list' sel_turn.id%}" class="btn waves-effect">Cancel</a>
                   </div>
                </div>
            </form>



        </div>
      </li>

    </ul>








    <div class="row">
        <form action="{% url 'tabor:issue_list_new' sel_turn.id %}" method="post">
                    {% csrf_token %}
                   <div class="row ">
                   <div class="input-field col s12" >
                       <i class="material-icons prefix">edit_mode_circle</i>
                       <textarea  name="notice" id="body" class="materialize-textarea"></textarea>
                       <label for="body">New</label>
                   </div>


                   <div class="input-field col s12 m6">
                        <i class="material-icons prefix">grade</i>
                        <select name="type_id">
                            {% for issue_type in issue_types %}
                            <option value="{{issue_type.id}}">{{issue_type.label}}
                            </option>

                            {% endfor %}
                        </select>
                       <label>typ</label>
                   </div>
                   <div class="input-field col s12 m6 align: center">

                         <button class="btn waves-effect"><i class="material-icons">input</i></button>
                   </div>
                </div>
        </form>
    </div>
    <ul class="collapsible" data-collapsible="accordion">
        {% for issue in issues %}
      <li>
        <div class="collapsible-header">

            <span class="badge">{{issue.moment}}</span>
                        <i class="material-icons">{{issue.type.icon}}</i>
                                {{issue.author}}</a>
            <blockquote style="border-left-color: {{issue.status.color}}">
            <p>{{issue.body}}</p>
            </blockquote>
        </div>
        <div class="collapsible-body">
            <div class="row align: center">
                <div class="col s4">
                <form action="{% url 'tabor:issue_change_status' sel_turn.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="status_label" value="seen">
                    <input type="hidden" name="issue_id" value="{{issue.id}}">
                    <button class="btn waves-effect orange"><i class="material-icons">visibility</i></button>
                </form>
                </div>
                <div class="col s4">
                <form action="{% url 'tabor:issue_change_status' sel_turn.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="status_label" value="checked">
                    <input type="hidden" name="issue_id" value="{{issue.id}}">
                    <button class="btn waves-effect green"><i class="material-icons">done</i></button>
                </form>
                </div>
                <div class="col s4">
                <form action="{% url 'tabor:issue_change_status' sel_turn.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="status_label" value="deleted">
                    <input type="hidden" name="issue_id" value="{{issue.id}}">
                    <button class="btn waves-effect black"><i class="material-icons">delete</i></button>
                </form>
                </div>
            </div>
        </div>
      </li>
        {% endfor %}
    </ul>


</div>


{% else %}
pro issue list je nutné se přihlásit
{% endif%}
{% endblock %}